version: "3.9"

services:
  apartment_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=rent_apartment_db
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5455:5432"

volumes:
  db: